### ISSUE TITLE
Beta Release Crashes on Launch

### ISSUE THREAD

**Issue by ghost** [Jakky27/UW-Plant-Map#13]
# Pre-issue checklist
- [x] Made sure software is up to date.
- [x] Tried reinstalling app again to see whether the bug still exists.

# Summary
The apk provided on the release page crashes on launch.

## What happens on launch

UI features are visible in the background. A map of the university washington loads. The app then closes and the error message "UW Plant Map has Stopped" is rendered on screen.

## What is expected 

UI and map loads and allows the user to navigate and use the application. 

Clear reproducing steps. Describes whether you can reproduce the bug, what method you used to interact with our app, what’s the actual results and your expected results.

# Steps for reproduction

1. Using the android device open chrome and navigate to the release [page](https://github.com/Jakky27/UW-Plant-Map/releases/tag/v1.0-beta).

2. Download the apk to the device by tapping on it. 

3. Tap the downloaded apk to open it.

3. If prompted grant Chrome permissions to install unknown applications.

4. When prompted tap install.

5. When finished tap done.

6. Navigate to Settings > Apps > UWPlantMap and grant all permissions.

7. Locate the installed application on the device and launch it.

# Additional information:
Device Model Number: SAMSUNG-SM-G930A
Android version 8.0.0

**Comment by kourbou** [comment]
The APK provided on the Beta Release page is out of date, and we've made changes to the application since. Can you try with the latest build off of CircleCI? You can download the generated app [here](https://369-256333205-gh.circle-artifacts.com/0/frontend/app/build/outputs/apk/debug/app-debug.apk). It should be built with the latest commit, available in the build artifacts of `build_frontend`.

**Comment by ghost** [comment]
I was able to install the app you linked in your last comment and the app launched without crashing. 

However I was required to disable Google Play Protect and I needed to uninstall all previous versions of the app I had on the device previously. 

Could you please update the release page to link to an apk that does not crash on launch and also make note of disabling play protect and uninstalling previous versions in your user documentation?

**Comment by kourbou** [comment]
Will do! Thank you!
